@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MWVkOTNiYjlkMzUyOGRhNDc2YzVhNGUiLCJuYW1lIjoiRmVybmFuZGEgU2FudG9zIE5hc2NpbWVudG8iLCJlbWFpbCI6ImZlcm5hbmRhQGVtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzIwMjk3NDYzLCJleHAiOjE3MjAzODM4NjN9.hTbWG74SrL8AdXIHFA1RZDdCp1gFHXIviii8b7h4N0w

POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Haliane Ferreira Pessoa Nascimento",
  "email": "haliane@email.com",
  "registry": "14254535",
  "password": "123@abc",
  "confirmPassword": "123@abc",
  "role": "admin"
}
###

GET {{baseUrl}}/users
Authorization: Bearer {{token}}
###

POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "fernanda@email.com",
  "password": "123@abc"
}
