@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MWVkOTNiYjlkMzUyOGRhNDc2YzVhNGUiLCJuYW1lIjoiRmVybmFuZGEgU2FudG9zIE5hc2NpbWVudG8iLCJlbWFpbCI6ImZlcm5hbmRhQGVtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzIwMjk3NDYzLCJleHAiOjE3MjAzODM4NjN9.hTbWG74SrL8AdXIHFA1RZDdCp1gFHXIviii8b7h4N0w

POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Ana Paula Santos Nascimento",
  "email": "anapaula10@email.com",
  "registry": "14254536",
  "password": "123@abc",
  "confirmPassword": "123@abc",
  "role": "user"
}
###

GET http://localhost:3000/users
###Authorization: Bearer {{token}}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "fernanda@email.com",
  "password": "123@abc"
}
